README.md
ec2/README.md
ec2/ec2-auto-recovery.json
vpc/DEV.md
vpc/README.md
vpc/vpc-2azs.json
vpc/vpc-3azs.json
vpc/vpc-nat-instance.json
wordpress/README.md
wordpress/wordpress-ha.json

added VPC templates

---

security/README.md
security/cloudtrail.json
security/config.json

added Config setup

---

vpc/README.md
vpc/vpc-nat-instance.json

fix sg of nat instance

---

vpc/vpc-nat-gateway.yaml

Thanks for all the great templates!
This should make the NAT Gateway template a bit more readable.

Simplify NAT Gateway template

---

security/README.md
security/cloudtrail.yaml
security/config.yaml

Allow CloudTrail and Config to store files on an external s3 bucket in another account.

Allow sensitive data to be stored on external s3 bucket

---

static-website/README.md
vpc/README.md

Thanks for publishing these! Here are a couple of fixes for stack names I noticed.

Fix stack names

---

vpc/vpc-flowlogs.yaml

This is a simple stack that builds on the VPC stack and adds network flow logs.

Stack to add flowlogs to VPC.

---

docs/wordpress.md
test/src/test/java/de/widdix/awscftemplates/wordpress/TestWordpressHA.java
wordpress/wordpress-ha-aurora.yaml

Added template for Wordpress with Aurora in addition to the old template using MySQL

Wordpress with Aurora

---

security/cloudtrail.yaml

This adds the option to define a log file name prefix.

This adds the optional parameter to define a log file name prefix

---

docs/vpc.md
ec2/ec2-auto-recovery.yaml
ecs/cluster.yaml
ecs/service-cluster-alb.yaml
ecs/service-dedicated-alb.yaml
jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml
security/auth-proxy-ha-github-orga.yaml
static-website/static-website.yaml
vpc/vpc-nat-instance.yaml
vpc/vpc-ssh-bastion.yaml
vpc/zone-legacy.yaml
vpc/zone-private.yaml
vpc/zone-public.yaml
wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

Ability to integrate Route53 more easily

Zone Template

---

wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

Added CloudWatch Alarms to monitor RDS instances/cluster

Monitor RDS

---

vpc/zone-legacy.yaml
vpc/zone-private.yaml
vpc/zone-public.yaml

(Run `yamllint folder/template.yaml` and `aws cloudformation validate-template --template-body file://folder/template.yaml` before you open a PR)
---
Small fix, so that Parameters for DNS are displayed in the right place on the form.

Fix ParameterGroups

---

ecs/cluster.yaml

(Run `yamllint folder/template.yaml` and `aws cloudformation validate-template --template-body file://folder/template.yaml` before you open a PR)
---
I found this useful, maybe worth merging with upstream.

send ecs logs to cloudwatch logs

---

state/s3.yaml

add access through CloudFront using Origin Access Identity

add access through cloudfront

---

state/rds-aurora.yaml
state/rds-postgres.yaml

Improve restore from snapshot for encrypted databases

---

wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

based on values from @ILLUMINICE https://github.com/widdix/aws-cf-templates/issues/174#issuecomment-395936455

Improve WordPress php settings 

---

ec2/ec2-auto-recovery.yaml
vpc/vpc-2azs-legacy.yaml
vpc/vpc-2azs.yaml
vpc/vpc-3azs-legacy.yaml
vpc/vpc-3azs.yaml
vpc/vpc-4azs-legacy.yaml
vpc/vpc-4azs.yaml
vpc/vpc-nat-gateway.yaml
vpc/vpc-nat-instance.yaml
vpc/vpc-ssh-bastion.yaml
wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

ClassB with VPC legacy templates

---

security/account-password-policy.yaml

Issue: A change in the parameter only updates the lambda function and never invokes the updated lambda function.
Fix: Update CFN resources. Pass the parameters to the Custom Resource and process them in the Lambda function as an event. This allows the change in the parameters to update the IAM policy.
---
(describe your change here)

Update Lambda Function code and Custom Resource.

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

[Security] jenkins/jenkins-ha* - Update Jenkins to 2.138.1

---

state/s3.yaml

Support for config and cloud trail

[Improvement] `state/s3` - Support for config and cloud trail

---

state/elasticache-memcached.yaml

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticache-cache-cluster.html#cfn-elasticache-cachecluster-numcachenodes

[Improvement] state/elasticache-memcached - Avoid a cache cluster replacement if NumCacheNodes changes

---

docs/state.md
state/rds-mysql.yaml
test/src/test/java/de/widdix/awscftemplates/state/TestRDSMySQL.java

[New Template] `rds-mysql` - RDS MySQL HA

---

docs/security.md
docs/state.md
security/kms-key.yaml
state/rds-aurora-serverless.yaml
state/rds-aurora.yaml
state/rds-mysql.yaml
state/rds-postgres.yaml
test/src/test/java/de/widdix/awscftemplates/security/TestKmsKey.java
test/src/test/java/de/widdix/awscftemplates/state/TestRDSAurora.java
test/src/test/java/de/widdix/awscftemplates/state/TestRDSAuroraServerless.java

Aurora Serverless

---

ecs/README.md
ecs/cluster.yaml

[Improvement] ecs/cluster - Migrate from ECS optimized Amazon Linux to Amazon Linux 2

---

docs/migrate-v5.md
docs/migrate-v6.md
docs/migrate-v7.md
docs/migrate-v8.md
docs/operations.md
ecs/README.md
ecs/cluster.yaml
mkdocs.yml
operations/backup-dynamodb.yaml
test/src/test/java/de/widdix/awscftemplates/vpc/TestVPC2AZsLegacy.java
test/src/test/java/de/widdix/awscftemplates/vpc/TestVPC3AZsLegacy.java
test/src/test/java/de/widdix/awscftemplates/vpc/TestVPC4AZsLegacy.java
vpc/vpc-2azs-legacy.yaml
vpc/vpc-2azs.yaml
vpc/vpc-3azs-legacy.yaml
vpc/vpc-3azs.yaml
vpc/vpc-4azs-legacy.yaml
vpc/vpc-4azs.yaml

This will contain all initial v8 changes

prepare v8 release

---

wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

https://wordpress.org/news/2018/12/wordpress-5-0-1-security-release/)

[Security] wordpress/wordpress-ha* - Update to WordPress 5.0.1

---

ec2/ec2-auto-recovery.yaml
ecs/cluster.yaml
jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml
security/auth-proxy-ha-github-orga.yaml
test/pom.xml
test/src/test/java/de/widdix/awscftemplates/AAWSTest.java
test/src/test/java/de/widdix/awscftemplates/ATest.java
test/src/test/java/de/widdix/awscftemplates/ec2/TestEC2AutoRecovery.java
vpc/vpc-nat-instance.yaml
vpc/vpc-ssh-bastion.yaml
vpc/vpc-vpn-bastion.yaml
wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

Fix IAM SSH access

---

docs/state.md
state/elasticache-redis.yaml
test/src/test/java/de/widdix/awscftemplates/state/TestElastiCacheRedis.java

New template for ElastiCache Redis with two nodes (Multi-AZ) and one shard.

Elasticache redis

---

ecs/cluster.yaml
jenkins/jenkins2-ha-agents.yaml

In cases of failures during message processing the message is now reprocessed much faster

[Improvement] ecs/cluster, jenkins/jenkins2-ha-agents - Improve SQS message polling

---

.travis.yml
ecs/cluster.yaml
jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml
security/auth-proxy-ha-github-orga.yaml
vpc/vpc-nat-instance.yaml
vpc/vpc-ssh-bastion.yaml
vpc/vpc-vpn-bastion.yaml
wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

[Bug Fix] * - Get rid of DesiredCapacity in auto scaling groups

---

security/cloudtrail.yaml

[Bug Fix] security/cloudtrail - Internal bucket with log prefix was not working

---

fargate/service-cloudmap.yaml
fargate/service-cluster-alb.yaml
fargate/service-dedicated-alb.yaml

[Bug Fix] fargate/service-* - Fix 0.5 CPU value

---

ecs/cluster.yaml
operations/backup-dynamodb-native.yaml
security/account-password-policy.yaml
state/elasticache-memcached.yaml
static-website/lambdaedge-index-document.yaml
wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

Update Lambda functions to node 8.10

---

ecs/cluster.yaml

Removing access to SQS and ASG from ECS instances.

improving IAM policy for ECS cluster instances

---

ec2/ec2-auto-recovery.yaml
ecs/cluster.yaml
jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml
security/auth-proxy-ha-github-orga.yaml
vpc/vpc-nat-instance.yaml
vpc/vpc-ssh-bastion.yaml
vpc/vpc-vpn-bastion.yaml
wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

[Bug Fix] * - Fixed missing logs:CreateLogGroup permission

---

.travis.yml
docs/state.md
operations/alert.yaml
operations/backup-dynamodb-native.yaml
state/dynamodb.yaml
state/s3.yaml

[Improvement] state/dynamodb - Enable AWS Backup

---

docs/state.md
state/s3.yaml
test/src/test/java/de/widdix/awscftemplates/vpc/TestVPCFlowLogsS3.java
vpc/vpc-flow-logs-s3.yaml

[Improvement] state/s3 - Additional access capability: FlowLogWrite

[New Template] vpc/vpc-flow-logs-s3 - Deliver VPC Flow Logs to S3

---

docs/state.md
state/rds-aurora-serverless-postgres.yaml
test/src/test/java/de/widdix/awscftemplates/state/TestRDSAuroraServerlessPostgres.java

[New Template] state/rds-aurora-serverless-postgres - RDS Aurora Serverless PostgreSQL

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://jenkins.io/changelog-stable//#v2.190.1

[Security] jenkins/* - Update Jenkins to 2.190.1

---

state/dynamodb.yaml
test/src/test/java/de/widdix/awscftemplates/state/TestDynamoDB.java

Adding DynamoDB Global Secondary Indexes.

[Improvement] state/dynamodb - Adding GSI

---

wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

https://wordpress.org/news/2019/12/wordpress-5-3-1-security-and-maintenance-release/

[Security] wordpress/* - Update WordPress to 5.3.1

---

static-website/static-website.yaml

Just notice a small typo and thought I could fix it quick

Fixed Small typo

---

ec2/README.md
ec2/ec2-auto-recovery.yaml
jenkins/README.md
jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml
security/README.md
security/auth-proxy-ha-github-orga.yaml
vpc/README.md
vpc/vpc-ssh-bastion.yaml
vpc/vpc-vpn-bastion.yaml
wordpress/README.md
wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

Updating to Amazon Linux 2.0.20191217.0

Updating to Amazon Linux 2.0.20191217.0

---

ecs/cluster.yaml
jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml
security/account-password-policy.yaml
state/elasticache-memcached.yaml
vpc/vpc-vpn-bastion.yaml
wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

Lambda@Edge remains on Node 10 because Node 12 is not yet supported

[Improvement] * - Update Lambda functions to Node 12

---

ec2/al2-mutable-private.yaml
ec2/al2-mutable-public.yaml

fixed
* `/var/log/messages`
* `/var/log/cron`
* `/var/log/secure`
* `/var/log/maillog`
added
* `/var/log/yum.log`

[Bug Fix] ec2/al2-mutable-* - Fix CloudWatch Unified Agent config

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://jenkins.io/changelog-stable//#v2.204.4

[Improvement] jenkins/* - Update Jenkins to 2.204.4

---

static-website/lambdaedge-index-document.yaml

https://aws.amazon.com/about-aws/whats-new/2020/03/lambda-at-edge-node12-python38/

[Improvement] static-website/lambdaedge-index-document - Update Lambda@Edge to Node.js 12

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://jenkins.io/changelog-stable//#v2.222.1

[Security] jenkins/* - Updaten Jenkins to 2.222.1

---

wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

https://wordpress.org/news/2020/03/adderley/

[Improvement] wordpress/ - Update WordPress to 5.4

---

operations/alb-access-logs-anonymizer.yaml

see https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html
TODOs:

[New Template] operations/alb-access-logs-anonymizer - Anonymize ALB Access Log

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.222.3

[Bug Fix] jenkins/* - Update Jenkins to 2.222.3

---

wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

https://wordpress.org/news/2020/04/wordpress-5-4-1/

[Security] wordpress/* - Update WordPress to 5.4.1

---

wordpress/README.md

---
(describe your change here)

Fix link to k6 docs

---

docs/operations.md
operations/terraform-state.yaml
test/src/test/java/de/widdix/awscftemplates/AAWSTest.java
test/src/test/java/de/widdix/awscftemplates/operations/TestTerraformState.java

Create S3 bucket and DynamoDB table to manage Terraform remote state. Use bucket policy to avoid leaking sensitive information stored in remote state. Also, encrypt sensitive data.

[New Template] operations/terraform-state.yaml

---

docs/operations.md
operations/terraform-state.yaml

Improving the bucket policy and docs for the S3 bucket optimized to store Terraform state.

[Improvement] operations/terraform-state - Improving bucket policy and docs

---

wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

https://wordpress.org/news/2020/06/wordpress-5-4-2-security-and-maintenance-release/

[Security] wordpress/* - Update WordPress to 5.4.2

---

security/auth-proxy-ha-github-orga.yaml

https://github.com/oauth2-proxy/oauth2-proxy/releases/tag/v6.0.0

[Security] security/auth-proxy-ha-github-orga - Update OAuth2 Proxy to 6.0.0

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.235.2

[Security] jenkins/* - Update Jenkins to 2.235.2

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.235.3

[Improvement] jenkins/* - Update Jenkins to 2.235.3

---

security/account-password-policy.yaml

https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-cis-controls.html#securityhub-cis-controls-1.9
https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-cis-controls.html#securityhub-cis-controls-1.10

[Security] security/account-password-policy - Make defaults comply with CIS 1.9 and 1.10

---

security/kms-key.yaml

https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-cis-controls.html#securityhub-cis-controls-2.8

[Security] security/kms-key - Comply with CIS 2.8

---

ec2/al2-mutable-private.yaml
ec2/al2-mutable-public.yaml
ec2/ec2-auto-recovery.yaml
ecs/cluster-cost-optimized.yaml
ecs/cluster.yaml
ecs/service-cluster-alb.yaml
ecs/service-dedicated-alb.yaml
fargate/service-cloudmap.yaml
fargate/service-cluster-alb.yaml
fargate/service-dedicated-alb.yaml
jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml
operations/alb-access-logs-anonymizer.yaml
operations/cloudfront-access-logs-anonymizer.yaml
security/account-password-policy.yaml
security/auth-proxy-ha-github-orga.yaml
security/cloudtrail.yaml
security/config.yaml
state/dynamodb.yaml
state/elasticache-memcached.yaml
static-website/lambdaedge-index-document.yaml
vpc/vpc-flow-logs.yaml
vpc/vpc-nat-instance.yaml
vpc/vpc-ssh-bastion.yaml
vpc/vpc-vpn-bastion.yaml
wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

This is an implementation of #464 (where we're still discussing the proposal).  I've never tried to run tests cases, but the PR does lint.

Permissions Boundary Infrastructure

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.235.4

[Security] jenkins/* - Update Jenkins to 2.235.4

---

wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

[Improvement] wordpress/* - Update WordPress to 5.5

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml
state/rds-aurora-serverless.yaml

https://www.jenkins.io/changelog-stable//#v2.235.5

[Security] jenkins/* - Update Jenkins to 2.235.5

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.249.1

[Security] jenkins/* - Update Jenkins to 2.249.1

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.249.2

[Bug Fix] jenkins/* - Update Jenkins to 2.249.2

---

wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

https://wordpress.org/news/2020/10/wordpress-5-5-2-security-and-maintenance-release/

[Security] wordpress/* - Update WordPress to 5.5.2

---

wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

https://wordpress.org/news/2020/10/wordpress-5-5-3-maintenance-release/

[Bug Fix] wordpress/* - Update WordPress to 5.5.3

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.249.3

[Bug Fix] jenkins/* - Update Jenkins to 2.249.3

---

.gitignore
ecs/cluster.yaml
ecs/service-dedicated-alb.yaml
fargate/cluster.yaml
fargate/service-dedicated-alb.yaml
security/waf.yaml
static-website/static-website.yaml
test/src/test/java/de/widdix/awscftemplates/ecs/TestECSService.java
test/src/test/java/de/widdix/awscftemplates/fargate/TestFargateService.java
test/src/test/java/de/widdix/awscftemplates/staticwebsite/TestStaticWebsite.java
wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

Adding a basic WAF to rate limit clients per source IP address.

[New Template] security/waf - Web Application Firewall (WAF)

---

state/elasticache-redis.yaml

Updating the available Redis versions.

[Improvement] state/elasticache-redis - Updating available Redis versions

---

fargate/service-cloudmap.yaml
fargate/service-cluster-alb.yaml
fargate/service-dedicated-alb.yaml

Migration guide: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/platform_versions.html#platform-version-migration

[Improvement] fargate/* - Update Platform version to 1.4.0

---

state/rds-postgres.yaml

Updating the available engine versions for RDS Postgres.

[Improvement] state/rds-postgres - Update engine versions

---

operations/terraform-state.yaml
security/cloudtrail.yaml
security/config.yaml
state/s3.yaml
static-website/static-website.yaml
vpc/vpc-2azs-legacy.yaml
vpc/vpc-3azs-legacy.yaml
vpc/vpc-4azs-legacy.yaml
vpc/vpc-flow-logs-s3.yaml
vpc/zone-legacy.yaml

see https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-s3-5

[Security] *  - Block all non https traffic to S3 buckets

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.263.1

[Improvement] jenkins/* - Update Jenkins to 2.263.1

---

wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

https://wordpress.org/news/2020/12/simone/

[Improvement] wordpress/* - Update WordPress to 5.6

---

state/elasticache-redis.yaml

Adds the option to run elasticache redis instanzes in different AZs for ha.

[Improvement] state/elasticache-redis: add MultiAZ option

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.263.2

[Security] jenkins/* - Update Jenkins to 2.263.2

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.263.3

[Security] jenkins/* - Update Jenkins to 2.263.3

---

wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

https://wordpress.org/news/2021/02/wordpress-5-6-1-maintenance-release/

[Bug Fix] wordpress/* - Update WordPress to 5.6.1

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.263.4

[Bug Fix] jenkins/* - Update to Jenkins 2.263.4

---

docs/vpc.md
security/kms-key.yaml
test/src/test/java/de/widdix/awscftemplates/vpc/TestHostedZone.java
vpc/zone-dnssec.yaml

[New Template] vpc/zone-dnssec - Adding support for DNSSEC

---

wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

https://wordpress.org/news/2021/02/wordpress-5-6-2-maintenance-release/

[Bug Fix] wordpress/* - Update WordPress to 5.6.2

---

wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

https://wordpress.org/news/2021/03/esperanza/

[Improvement] wordpress/* - Update WordPress to 5.7

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.277.1

[Improvement] jenkins/* - Update Jenkins to 2.277.1

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.277.2

[Security] jenkins/* Update Jenkins to 2.277.2

---

state/documentdb.yaml
state/rds-aurora-serverless-postgres.yaml
state/rds-aurora-serverless.yaml
state/rds-aurora.yaml
state/rds-mysql.yaml
state/rds-postgres.yaml
state/secretsmanager-dbsecret.yaml
test/src/test/java/de/widdix/awscftemplates/state/TestDocumentDB.java
test/src/test/java/de/widdix/awscftemplates/state/TestRDSAurora.java
test/src/test/java/de/widdix/awscftemplates/state/TestRDSAuroraServerless.java
test/src/test/java/de/widdix/awscftemplates/state/TestRDSAuroraServerlessPostgres.java
test/src/test/java/de/widdix/awscftemplates/state/TestRDSMySQL.java
test/src/test/java/de/widdix/awscftemplates/state/TestRDSPostgres.java

[Improvement] state/* - Add Secrets Manager Secret support

---

wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

https://wordpress.org/news/2021/04/wordpress-5-7-1-security-and-maintenance-release/

[Security] wordpress/* - Update WordPress to 5.7.1

---

state/documentdb.yaml
state/elasticache-memcached.yaml
state/elasticsearch.yaml
state/rds-aurora-serverless-postgres.yaml
state/rds-aurora.yaml
state/rds-mysql.yaml
state/rds-postgres.yaml

Parameter version updates for all latest major Engine Versions of the templates in state.
(Run `yamllint folder/template.yaml`, `cfn-lint -i E1019 E3002 E2520 -t folder/template.yaml`, and `aws cloudformation validate-template --template-body file://folder/template.yaml` before you open a PR) 
✅ 
✅

Parameter version updates for all latest major Engine Versions

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.277.3

[Security] jenkins/* - Update Jenkins to 2.277.3

---

docs/ecs.md
docs/fargate.md
docs/security.md
docs/state.md
docs/static-website.md
docs/wordpress.md
security/waf-legacy.yaml
security/waf.yaml

https://aws.amazon.com/waf/features/bot-control/

[Improvement] security/waf - Support Bot Control

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.277.4

[Bug Fix] jenkins/* - Update Jenkins to 2.277.4

---

wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

https://wordpress.org/news/2021/05/wordpress-5-7-2-security-release/

[Security] wordpress/* - Update WordPress to 5.7.2

---

wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

https://github.com/wp-cli/wp-cli/releases/tag/v2.5.0

[Improvement] wordpress/* - Update WP-CLI to 2.5.0

---

operations/alb-access-logs-anonymizer.yaml
operations/cloudfront-access-logs-anonymizer.yaml

* [Bug Fix] operations/alb-access-logs-anonymizer - Ignore empty files
* [Bug Fix] operations/cloudfront-access-logs-anonymizer - Ignore empty files

[Bug Fix] operations/*-access-logs-anonymizer - Ignore empty files

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.289.1

[Improvement] jenkins/* - Update to Jenkins 2.289.1

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml
wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

[Bug Fix] jenkins/* - Clean yum cache after enabling Amazon Linux extras
[Bug Fix] wordpress/* - Clean yum cache after enabling Amazon Linux extras
fixes #550

Clean yum cache after enabling Amazon Linux extras

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

[Bug Fix] jenkins/* - Install Jenkins plugins via Plugin Installation Manager Tool for Jenkins

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.289.2

[Security] jenkins/* - Update Jenkins to 2.289.2

---

ec2/README.md
ecs/README.md
ecs/cluster-cost-optimized.yaml
ecs/cluster.yaml
jenkins/README.md
jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml
security/README.md
security/auth-proxy-ha-github-orga.yaml
vpc/README.md
vpc/vpc-ssh-bastion.yaml
vpc/vpc-vpn-bastion.yaml
wordpress/README.md
wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

[Security] ecs/* - Update Amazon Linux 2 ECS-optimized to 20210623

[Security] * - Update Amazon Linux 2 to 20210617.0

---

.github/workflows/ci.yml
jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.289.3

[Improvement] jenkins/* - Update Jenkins to 2.289.3

---

wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

https://wordpress.org/news/2021/07/tatum/

[Improvement] wordpress/* - Update WordPress to 5.8

---

docs/vpc.md
vpc/vpc-vpn-bastion.yaml

https://www.softether.org/5-download/history

[Security] vpc/vpc-vpn-bastion - Update SoftEther to v4.38-9760

---

jenkins/jenkins2-ha-agents.yaml

[Bug Fix] jenkins/jenkins-ha-agents - Workaround AWS Ruby SDK breaking change 

---

wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

https://wordpress.org/news/2021/09/wordpress-5-8-1-security-and-maintenance-release/

[Security] wordpress/* - Update WordPress to 5.8.1

---

jenkins/jenkins2-ha-agents.yaml

[Bug Fix] jenkins/jenkins-ha-agents - Workaround AWS Ruby SDK breaking change part 2

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://github.com/jenkinsci/plugin-installation-manager-tool/releases/tag/2.11.0

[Improvement] jenkins/* - Update Plugin Installation Manager Tool for Jenkins to 2.11.0

---

ec2/README.md
ecs/README.md
ecs/cluster-cost-optimized.yaml
ecs/cluster.yaml
jenkins/README.md
jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml
security/README.md
security/auth-proxy-ha-github-orga.yaml
vpc/README.md
vpc/vpc-ssh-bastion.yaml
vpc/vpc-vpn-bastion.yaml
wordpress/README.md
wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

[Security] ecs/* - Update Amazon Linux 2 ECS-optimized to 20210902

[Security] * - Update Amazon Linux 2 to 20210813.1

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.303.3

[Security] jenkins/* - Update Jenkins to 2.303.3

---

wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

[**(Override all values in parentheses)**
---
(describe your change here)
](https://wordpress.org/news/2021/11/wordpress-5-8-2-security-and-maintenance-release/)

[Security] wordpress/* - Update WordPress to 5.8.2

---

ec2/README.md
ecs/README.md
ecs/cluster-cost-optimized.yaml
ecs/cluster.yaml
jenkins/README.md
jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml
security/README.md
security/auth-proxy-ha-github-orga.yaml
vpc/README.md
vpc/vpc-nat-instance.yaml
vpc/vpc-ssh-bastion.yaml
vpc/vpc-vpn-bastion.yaml
wordpress/README.md
wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

[Security] ecs/cluster* - Update Amazon Linux 2 ECS-optimized to 20211115
[Security] vpc/vpc-nat-instance - Update Amazon Linux NAT-optimized to 20211015.1

[Security] * - Update Amazon Linux 2 to 20211103.0

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.319.1

[Improvement] jenkins/* - Update Jenkins to 2.319.1

---

wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

Updating to Wordpress 5.8.3

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

Updating to Jenkins 2.319.2

---

.gitignore
ec2/README.md
ec2/al2-mutable-private.yaml
ec2/al2-mutable-public.yaml
jenkins/README.md
jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml
security/README.md
security/auth-proxy-ha-github-orga.yaml
vpc/README.md
vpc/vpc-ssh-bastion.yaml
vpc/vpc-vpn-bastion.yaml
wordpress/README.md
wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

Updating to Amazon Linux 2.0.20211223.0.

Updating to Amazon Linux 2.0.20211223.0

---

ec2/README.md
ec2/al2-mutable-private.yaml
ec2/al2-mutable-public.yaml
jenkins/README.md
jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml
security/README.md
security/auth-proxy-ha-github-orga.yaml
vpc/README.md
vpc/vpc-ssh-bastion.yaml
vpc/vpc-vpn-bastion.yaml
wordpress/README.md
wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

Updating to Amazon Linux 2.0.20220207.1

Updating to Amazon Linux 2.0.20220207.1

---

wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

[Security] wordpress - Wordpress 5.9.1

---

ec2/README.md
ec2/al2-mutable-private.yaml
ec2/al2-mutable-public.yaml
jenkins/README.md
jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml
security/README.md
security/auth-proxy-ha-github-orga.yaml
vpc/README.md
vpc/vpc-ssh-bastion.yaml
vpc/vpc-vpn-bastion.yaml

Updating to Amazon Linux 2.0.20220218.1

[Security] * - Updating to Amazon Linux 2.0.20220218.1

---

state/rds-postgres.yaml

Updating the available versions of PostgreSQL for RDS.

Updating RDS PostgreSQL versions

---

ec2/README.md
ec2/al2-mutable-private.yaml
ec2/al2-mutable-public.yaml
jenkins/README.md
jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml
security/README.md
security/auth-proxy-ha-github-orga.yaml
vpc/README.md
vpc/vpc-ssh-bastion.yaml
vpc/vpc-vpn-bastion.yaml
wordpress/README.md
wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

Updating to Amazon Linux 2.0 20220218.3

Updating to Amazon Linux 2.0 20220218.3

---

vpc/vpc-endpoint.yaml

Update supported service names of VPC interface endpoints.

[Improvement] vpc/vpc-endpoint - Update supported service names

---

ec2/README.md
ec2/al2-mutable-private.yaml
ec2/al2-mutable-public.yaml
ecs/README.md
ecs/cluster-cost-optimized.yaml
ecs/cluster.yaml
jenkins/README.md
jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml
security/README.md
security/auth-proxy-ha-github-orga.yaml
vpc/README.md
vpc/vpc-ssh-bastion.yaml
vpc/vpc-vpn-bastion.yaml
wordpress/README.md
wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

Updating to Amazon Linux 2.0.20220316.0.

[Security] * - Updating to Amazon Linux 2.0.20220316.0

---

state/rds-postgres.yaml

Removing unsupported PostgreSQL engine versions.

Updating PostgreSQL engine version

---

state/dynamodb.yaml

Adding parameters to be able to configure the index names and projection types.

DynamoDB: configure index name and projection type

---

state/dynamodb.yaml

Adding local secondary indexes for DynamoDB.

Adding DynamoDB Local Secondary Indexes

---

jenkins/README.md
jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml
security/README.md
security/auth-proxy-ha-github-orga.yaml
vpc/README.md
vpc/vpc-ssh-bastion.yaml
vpc/vpc-vpn-bastion.yaml
wordpress/README.md
wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

Updating to Amazon Linux 2.0.20220426.0

[Security] *- Updating to Amazon Linux 2.0.20220426.0

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.332.3

[Improvement] jenkins/* - Update Jenkins to 2.332.3

---

wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

https://wordpress.org/news/2022/04/wordpress-5-9-3-maintenance-release/

[Security] wordpress/* - Update WordPress to 5.9.3

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.346.1

[Security] jenkins/* - Update Jenkins to 2.346.1

---

wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

https://wordpress.org/news/2022/05/arturo/

[Improvement] wordpress/* - Update WordPress to 6.0

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.346.2

[Bug Fix] jnkins/* - Update Jenkins to 2.346.2

---

wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

https://wordpress.org/news/2022/07/wordpress-6-0-1-maintenance-release/

[Bug Fix] wordpress/* - Update WordPress to 6.0.1

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.346.3

[Bug Fix] jenkins/* - Update Jenkins to 2.346.3

---

wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

https://wordpress.org/news/2022/08/wordpress-6-0-2-security-and-maintenance-release/

[Security] wordpress/* - Update WordPress to 6.0.2

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.361.1

[Improvement] jenkins/* - Update Jenkins to 2.361.1

---

ecs/cluster-cost-optimized.yaml
ecs/cluster.yaml
jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml
security/auth-proxy-ha-github-orga.yaml
vpc/README.md
vpc/vpc-nat-instance.yaml
vpc/vpc-ssh-bastion.yaml
vpc/vpc-vpn-bastion.yaml
wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

[Improvement] * - Support new region me-central-1

[Security] * - Update Amazon Linux 2 / AL2 ECS / AL1 NAT

---

security/config.yaml
state/dynamodb.yaml

see https://aws.amazon.com/blogs/mt/service-notice-upcoming-changes-required-for-aws-config/

[Bug Fix] security/config - Replace deprecated policy AWSConfigRole

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.361.3

[Bug Fix] jenkins/* - Update Jenkins to 2.361.3

---

wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

https://wordpress.org/news/2022/11/misha/

[Improvement] wordpress/* - Update WordPress to 6.1

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable/#v2.361.4

[Bug Fix] jenkins/* - Update Jenkins to 2.361.4

---

wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

https://wordpress.org/news/2022/11/wordpress-6-1-1-maintenance-release/

[Bug Fix] wordpress/* - Update WordPress to 6.1.1

---

ecs/cluster-cost-optimized.yaml
ecs/cluster.yaml
jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml
security/auth-proxy-ha-github-orga.yaml
vpc/README.md
vpc/vpc-nat-instance.yaml
vpc/vpc-ssh-bastion.yaml
vpc/vpc-vpn-bastion.yaml
wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

[Improvement] * - Support new regions eu-central-2 and eu-south-2

[Security] * - Update Amazon Linux 2 / AL2 ECS (#655)

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.375.1

[Improvement] jenkins/* - Update Jenkins to 2.375.1

---

ecs/cluster-cost-optimized.yaml
ecs/cluster.yaml
jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml
security/auth-proxy-ha-github-orga.yaml
vpc/README.md
vpc/vpc-nat-instance.yaml
vpc/vpc-ssh-bastion.yaml
vpc/vpc-vpn-bastion.yaml
wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

[Improvement] * - Support new regions ap-south-2

[Security] * - Update Amazon Linux 2 / AL2 ECS

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.375.2

[Bug Fix] jenkins/* - Update Jenkins to 2.375.2

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.375.3

[Bug Fix] jenkins/* - Update Jenkins to 2.375.3

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://github.com/jenkinsci/plugin-installation-manager-tool/releases/tag/2.12.11

[Bug Fix] jenkins/* - Update Plugin Installation Manager Tool for Jenkins to 2.12.11

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.387.1

[Security] jenkins/* - Update Jenkins to 2.387.1

---

wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

https://wordpress.org/news/2023/03/dolphy/

[Improvement] wordpress/* - Update WordPress to 6.2

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.387.2

[Bug Fix] jenkins/* - Update Jenkins to 2.387.2

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.401.1

[Improvement] jenkins/* - Update Jenkins to 2.401.1

---

operations/github-openid-connect.yaml

https://github.blog/changelog/2023-06-27-github-actions-update-on-oidc-integration-with-aws/

[Bug Fix] operations/github-openid-connect - Fix thumbprints

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.401.2

[Improvement] jenkins/* - Update Jenkins to 2.401.2

---

docs/vpc.md
vpc/vpc-vpn-bastion.yaml

https://www.softether.org/5-download/history

[Security] vpc/vpc-vpn-bastion = Update SoftEther to 4.42

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.401.3

[Security] jenkins/* - Update Jenkins to 2.401.3

---

wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

https://wordpress.org/news/2023/08/lionel/

[Improvement] wordpress/* - Update WordPress to 6.3

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.414.1

[Security] jenkins/* - Update Jenkins to 2.414.1

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.414.2

[Security] jenkins/* - Update Jenkins to 2.414.2

---

wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

https://wordpress.org/news/2023/10/wordpress-6-3-2-maintenance-and-security-release/

[Security] wordpress/* - Update Wordpress to 6.3.2

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.414.3

[Security] jenkins/* - Update Jenkins to 2.414.3

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml
security/securityhub-controls.yaml

https://www.jenkins.io/changelog-stable//#v2.426.1

[Security] jenkins/* - Update Jenkins to 2.426.1

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://github.com/jenkinsci/plugin-installation-manager-tool/releases/tag/2.12.14

[Improvement] jenkins/* - Update Plugin Installation Manager Tool for Jenkins to 2.12.14

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.426.2

[Bug Fix] jenkins/* - Update Jenkins to 2.426.2

---

jenkins/jenkins2-ha-agents.yaml
jenkins/jenkins2-ha.yaml

https://www.jenkins.io/changelog-stable//#v2.426.3

[Security] jenkins/* - Update Jenkins to 2.426.3

---

wordpress/wordpress-ha-aurora.yaml
wordpress/wordpress-ha.yaml

https://wordpress.org/news/2024/01/wordpress-6-4-3-maintenance-and-security-release/

[Security] wordpress/* - Update WordPress to 6.4.3
