jenkins/jenkins2-ha.json
Changed to use official LTS yum repository for Jenkins installation instead of specific Jenkins version.
Ref: https://wiki.jenkins-ci.org/display/JENKINS/Installing+Jenkins+on+Red+Hat+distributions#InstallingJenkinsonRedHatdistributions-Installationofastableversion
=> Use yum repo instead of a specific Jenkins version

wordpress/README.md
This change makes each certificate clearer. I wasted half an hour because of a mis-named certificate in the wrong region. This phrasing should prevent such mistakes for future users.
- clarify which certificate is for the ELB.
- clarify which certificate is for CloudFront (and why)
=> Clarify certificates in wordpress steps

static-website/static-website.yaml
Before this change, static websites deployed using this template would not support http2. Here is a handy tool to test whether a given site is supporting http2: https://tools.keycdn.com/http2-test
In september 2016 CloudFront started supporting HTTP2 with graceful fallback to older versions. 
https://aws.amazon.com/blogs/aws/new-http2-support-for-cloudfront/
The HttpVersion parameter in the CloudFormation CloudFront configuration object is optional, and when not specified it defaults to the older value.
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distributionconfig.html
This change specifies HttpVersion as http2 for the CloudFront distributions, which will give better performance and doesn't cost any extra.
Thanks for publishing these templates!
=> Enable http2 for cloudfront static sites.

ecs/service-cluster-alb.yaml
Issue: https://github.com/widdix/aws-cf-templates/issues/71
Now will apply the same Conditions property as the HTTP Listener.
This allows the LoadBalancerHostPattern parameter to be used to
route traffic on the ALB.
=> Fixed HTTPS Load Balancer Listener Rule

ecs/service-cluster-alb.yaml, ecs/service-dedicated-alb.yaml
Added parameters to be able to configure the Deregistration Delay for the Target Group. Decreases time needed for deployment of new images for a service.
=> added parameter for ALB deregistration delay

static-website/static-website.yaml
The string concatenation used to form the origin domain name and path in CloudFront is broken for regions that use the .region instead of the -region format (Ohio, Canada, Mumbai, Seoul, Frankfurt and London)
http://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteEndpoints.html
The two general forms of an Amazon S3 website endpoint are as follows:
bucket-name.s3-website-region.amazonaws.com (dash region)
bucket-name.s3-website.region.amazonaws.com (dot region)
Listing of all region endpoints
http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_website_region_endpoints
This is a particularly fun error to debug as CloudFront will error saying that it can't reach the origin server and when you look at the path it looks right on first glance (long string with only a dot/dash in the …
=> static website template: support both dot region and dash region s3 website endpoints

ecs/cluster.yaml
The problem with the current implementation is that we scale up and down on two metrics (CPU and memory reservation). This can lead to situation where memory is low but we scale down based on CPU which results in constant scale up/down activities.
The solution is based on http://garbe.io/blog/2017/04/12/a-better-solution-to-ecs-autoscaling/ by @pgarbe
=> improves ECS cluster scaling

.travis.yml
fix cloudformation validate-template check refs #113 bit still contains the issue when the template is longer than 51200 bytes
=> Travis Validation Failures

security/cloudtrail.yaml, security/config.yaml
The External Bucket Parameters weren't set up with a default, thus they weren't optional.
=> Make CloudTrail and Config External Bucket optional

jenkins/jenkins2-ha-agents.yaml, jenkins/jenkins2-ha.yaml
Because password was double quoted in password reset - it was failing if there is $ in password. I changed to single quotes and checked that everywhere else single quotes already used.
PS: `yamllint` (obviously) and `aws cloudformation validate-template` (not sure why the latter) both fail on the original templates.
=> Bug fix: Jenkins stack creation failed with $ in Jenkins admin password

ecs/cluster.yaml
* Removed deregistration delay from default target group.
* Updated AWS Ruby SDK
=> ECS: removed default target group connection draining, updated AWS SDK

wordpress/wordpress-ha.yaml
Fix SurgeQueueLength comparisonOperator value
(Run `yamllint folder/template.yaml` and `aws cloudformation validate-template --template-body file://folder/template.yaml` before you open a PR)
---
CloudFormation will end-up in a `CREATE_FAILED` status, because the `comparisonOperator` is set to the wrong value. 
This commit solves the error:
```
1 validation error detected: Value 'SurgeQueueLength' at 'comparisonOperator' failed to satisfy constraint: Member must satisfy enum value set: [GreaterThanThreshold, LessThanThreshold, LessThanOrEqualToThreshold, GreaterThanOrEqualToThreshold]
```
=> Fix SurgeQueueLength comparisonOperator value

ecs/cluster.yaml
(Run `yamllint folder/template.yaml` and `aws cloudformation validate-template --template-body file://folder/template.yaml` before you open a PR)
---
Hi there,
Adding log retention for the log group that is used by the Lambda lifecycle function.
This change might break updating the existing CloudFormation stack, because the log group is already created by a previous CloudFormation run. 
Decided to set the `DeletionPolicy` to `Retain`, so that log retention stays there if a stack is deleted (_CF's default behaviour is setting `Expire Events After` to `Never expire`_ ).
Greetz, Siert
=> Set logretention for Lambda LogGroup

wordpress/wordpress-ha-aurora.yaml, wordpress/wordpress-ha.yaml
Makes the wordpress templates have the machines install php-xmlrpc so that the xmlrpc api of wordpress is usable
=> [Improvement] wordpress/* - Enable xmlrpc for WordPress API

jenkins/jenkins2-ha-agents.yaml
if the agent was not booting fast enough we scaled down because of no active build. we now scale down if there is no active build and no queued build.
=> [Bug Fix] jenkins/jenkins-ha-agents - Scaling was broken when agents took aa long time to boot

test/src/test/java/de/widdix/awscftemplates/wordpress/TestWordpressHA.java, wordpress/wordpress-ha-aurora.yaml, wordpress/wordpress-ha.yaml
As CloudFormation allows us to use EFS provisioned throughput now, I've added an optional parameter  `EFSProvisionedThroughputInMibps`.
A Custom Resource is used to calculate the threshold for the CloudWatch alarm.
=> [Improvement] wordpress/* -  Optional EFS provisioned throughout

ecs/cluster.yaml, ecs/service-dedicated-alb.yaml, fargate/service-dedicated-alb.yaml, jenkins/jenkins2-ha-agents.yaml, jenkins/jenkins2-ha.yaml, security/auth-proxy-ha-github-orga.yaml, wordpress/wordpress-ha-aurora.yaml, wordpress/wordpress-ha.yaml
* [Improvement] `jenkins/jenkins-ha*` - Optional support for ALB access logging and idle timeout
* [Improvement] `auth-proxy-ha-github-orga` - Optional support for ALB access logging and idle timeout
* [Improvement] `wordpress/wordpress-ha*` - Optional support for ALB access logging and idle timeout
=> Enable access logging for load balancers

state/elasticache-redis.yaml, test/src/test/java/de/widdix/awscftemplates/state/TestElastiCacheRedis.java
Simplifying the default for ElastiCache Redis. See https://github.com/widdix/aws-cf-templates/issues/263 for more details.
=> Redis: set default for AuthToken

docs/fargate.md, fargate/service-cloudmap.yaml, fargate/service-cluster-alb.yaml, fargate/service-dedicated-alb.yaml, test/src/test/java/de/widdix/awscftemplates/ATest.java, test/src/test/java/de/widdix/awscftemplates/fargate/TestFargateService.java, vpc/cloudmap-private.yaml
Adding service discovery aka. Cloud Map to the Fargate templates.
=> Fargate service with Cloud Map support

ecs/cluster.yaml
The ASG lifecycle hook has been deregistering the instance from the ECS cluster so far. This caused problems as a bug in ECS caused the instance to get stuck in state `running` even after the instance had been terminated. Therefore, I'm removing the ECS instance de-registration from the ASG lifecycle hook. The ECS agent will deregister the instance automatically during the shutdown of the instance.
=> [Bug Fix] ecs/cluster - Fix deregistration bug during scale in

ecs/README.md, ecs/cluster.yaml
=> [Security] ecs/cluster - Update ECS-optimized Amazon Linux 2 to 2.0.20190301

ecs/cluster.yaml, ecs/lambda-drain-instance/README.md, ecs/lambda-drain-instance/deploy.sh, ecs/lambda-drain-instance/lib.js, ecs/lambda-drain-instance/package-lock.json, ecs/lambda-drain-instance/package.json
Rewrite of the Auto Scaling Lifecycle Hook. Use Lambda instead of script running on EC2. Support instance draining timeouts up to 24 hours.
=> ECS: Auto Scaling Lifecycle Hook for Instance Draining based on Lambda

security/account-password-policy.yaml
It was not possible to disable the expiry of passwords `MaxPasswordAge = 0` nor to disable the password reuse prevention `PasswordReusePrevention = 0`. Both parameters must be `> 0` (see https://docs.aws.amazon.com/IAM/latest/APIReference/API_PasswordPolicy.html). But both parameters are also optional.
=> [Bug Fix] security/account-password-policy - allow to disable MaxPasswordAge and PasswordReusePrevention

state/rds-aurora-serverless.yaml
https://aws.amazon.com/about-aws/whats-new/2019/04/amazon_aurora_serverless_now_supports_a_minimum_capacity_of_1_unit_and_a_new_scaling_option/
=> [Improvement] state/rds-aurora-serverless - Support capacity of 1

ecs/cluster.yaml
The Auto Scaling Group managing the instance for the ECS cluster was using simple scaling. Unfortunately, a waiting lifecycle hook blocks any scaling actions. So while waiting for all tasks getting stopped on an ECS instance, no other scaling action was possible.
This change replaces simple scaling with step scaling. With step scaling a scaling action is possible even while a lifecycle hook is in state waiting.
=> [Improvement] ecs/cluster - Avoid scaling deadlock

state/rds-aurora-serverless.yaml
CloudFOrmation does not support updates to Aurora Serverless clusters if `Port`, `PreferredBackupWindow`, or `PreferredMaintenanceWindow` are set no matter if those attributes change or not.
=> [Bug Fix] state/rds-aurora-serverless - Workaround for CloudFormation bug

wordpress/wordpress-ha-aurora.yaml, wordpress/wordpress-ha.yaml
…up failed with exception An error occurred (AccessDeniedException) when calling the CreateLogGroup operation: User: arn:aws:sts::XXXXXXXXXXXX:assumed-role/wordpress-WebServerIAMRole-XXXXXXXXXXXXX/i-XXXXXXXXXXXXXXXXX is not authorized to perform: logs:CreateLogGroup on resource: arn:aws:logs:us-east-1:XXXXXXXXXXXX:log-group:wordpress-WebServerLogs-XXXXXXXXXXXXX:log-stream: error because of missing permissions
---
(describe your change here)
Fixed error related to missing …
=> [Bug Fix] wordpress/* - Fixed missing logs:CreateLogGroup permission

ecs/README.md, ecs/cluster.yaml
Updating ECS AMI to `amzn2-ami-ecs-hvm-2.0.20190510-x86_64-ebs`.
=> [Improvement] ecs/cluster - Updating ECS AMI to 2.0.20190510

static-website/lambdaedge-index-document.yaml
Lambda on edge did not behave correctly for filenames with caps letters, for instance "/pic.JPG" would be redirected to "/pic.JPG/"
=> [Bug Fix] static-website/lambdaedge-index-document - Support uppercase file endings

security/cloudtrail.yaml
Added option to record S3 data events with CloudTrail as well. Default is `false` as depending on the amount of S3 requests, recording the data events might be costly.
=> [Improvement] security/cloudtrail - Recording S3 data events

docs/migrate-v10.md, fargate/service-cloudmap.yaml, fargate/service-cluster-alb.yaml, fargate/service-dedicated-alb.yaml
We did not use the term `ambassador container` correctly. Therefore, renaming to `proxy container`.
=> [Improvement] fargate/service-* - Renaming ambassador container to proxy container

.travis.yml, docs/migrate-v10.md, ec2/ec2-auto-recovery.yaml, ecs/cluster.yaml, ecs/service-cluster-alb.yaml, ecs/service-dedicated-alb.yaml, fargate/service-cloudmap.yaml, jenkins/jenkins2-ha-agents.yaml, jenkins/jenkins2-ha.yaml, mkdocs.yml, operations/backup-dynamodb-native.yaml, security/account-password-policy.yaml, security/auth-proxy-ha-github-orga.yaml, security/config.yaml, state/dynamodb.yaml, state/elasticache-memcached.yaml, static-website/lambdaedge-index-document.yaml, vpc/vpc-flow-logs.yaml, vpc/vpc-nat-instance.yaml, vpc/vpc-ssh-bastion.yaml, vpc/vpc-vpn-bastion.yaml, wordpress/wordpress-ha-aurora.yaml, wordpress/wordpress-ha.yaml
Breaking change because we reduce the permissions if SSM is enabled.
Workaround: Passt SSM managed policy as new parameter
=> Get rid of managed policies

vpc/vpc-endpoint.yaml
Fixes `An error occurred (ValidationError) when calling the CreateChangeSet operation: Parameters: [ParentClientStack] must have values`
=> Give ParentClientStack default empty for optional

ecs/README.md, ecs/cluster.yaml
Update ECS optimized Amazon Linux 2 to 20200108 .
=> [Security] ecs/cluster - Update ECS optimized Amazon Linux 2 to 20200108 

vpc/vpc-2azs.yaml, vpc/vpc-3azs.yaml, vpc/vpc-4azs.yaml
We have a use case where we're using one of your VPC templates, and building upon the core network resources with another template to create some additional in-house network resources (NAT gateway, routes to other clouds etc.).
One of the templates needs to access the dynamically created InternetGateway ID in order to add some custom routing rules.
The current workaround is messy and requires manually extracting the InternetGateway ID and adding it as a parameter to the second template. I'm hoping this PR is general purpose enough and that the InternetGateway isn't deliberately excluded from the exports? Thanks!
Workaround:
```yaml
Parameters:
ParentVPCStack:
Description: 'Stack name of parent VPC stack based on vpc/vpc-*azs.yaml template.'
Type: String
InternetGateway:
Description: …
```
=> [Improvement] vpc/vpc* - Add InternetGateway export

security/auth-proxy-ha-github-orga.yaml
https://github.com/oauth2-proxy/oauth2-proxy/releases/tag/v5.1.0
=> [Improvement] security/auth-proxy-ha-github-orga - Update OAuth2 Proxy to 5.1.0

state/rds-postgres.yaml
If you want to [force_ssl](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html#PostgreSQL.Concepts.General.SSL.Requiring) on RDS Postgres, you have to do so by providing a `DBParameterGroup`.  This patch add the option to pass such a group value (with the backwards-compatible default) to the `state/rds-postgres` template.
Obviously, this would work with any parameter group (even those unrelated to `force_ssl`), but here's an example with `force_ssl`:
```
ForceSSLParameterGroup:
Type: 'AWS::RDS::DBParameterGroup'
Properties:
Description: 'Applies rds.force_ssl to pgSQL servers.'
Family: 'postgres10'
Parameters:
rds.force_ssl: '1'
Database:
Type: 'AWS::CloudFormation::Stack'
Properties:
Parameters:
...
DBParameterGroupName: !Ref ForceSSLParameterGroup
TemplateURL: …
```
=> [Improvement] state/rds-postgres - Add support for parameter and option groups

security/auth-proxy-ha-github-orga.yaml
https://github.com/oauth2-proxy/oauth2-proxy/releases/tag/v5.1.1
=> [Security] security/auth-proxy-ha-github-orga - Update OAuth2 Proxy to 5.1.1

static-website/static-website.yaml
S3 buckets have two domain names: a global and a regional one. Buckets which have been just created may lead to a redirect when using the global domain name. The static website would not work then unless you wait some hours. The regional domain name works immediately.
=> Use regional domain name of S3 bucket in CloudFront

operations/alb-access-logs-anonymizer.yaml, operations/cloudfront-access-logs-anonymizer.yaml
If a original file was anoymized but the event was dispatched twice a NoSuchKey error was thrown (AccessDenied to be more pricise but I fixed that as well).
Now, if we receive a NoSuchKey error for the original key, we check if the anonymized key already exist.
If yes, done. Work is already done.
If no, throw error again.
I also fixed an issue with they way errors are not "piped" thrhough when connection streams with .pipe().
=> [Bug Fix] operations/*-access-logs-anonymizer - Improve error handling when file was already anonymized

ec2/README.md, ec2/al2-mutable-private.yaml, ec2/al2-mutable-public.yaml, ec2/ec2-auto-recovery.yaml, ecs/README.md, ecs/cluster-cost-optimized.yaml, ecs/cluster.yaml, jenkins/README.md, jenkins/jenkins2-ha-agents.yaml, jenkins/jenkins2-ha.yaml, security/README.md, security/auth-proxy-ha-github-orga.yaml, vpc/README.md, vpc/vpc-nat-instance.yaml, vpc/vpc-ssh-bastion.yaml, vpc/vpc-vpn-bastion.yaml, wordpress/README.md, wordpress/wordpress-ha-aurora.yaml, wordpress/wordpress-ha.yaml
* AL2 to 20200520.1
* AL2 ECS to 20200603
* AL1 NAT 2018.03.0 to 20200602.1
=> [Security] * - Update Amazon Linux AMIs

state/documentdb.yaml, state/elasticache-memcached.yaml, state/elasticache-redis.yaml, state/elasticsearch.yaml, state/rds-aurora-serverless-postgres.yaml, state/rds-aurora-serverless.yaml, state/rds-aurora.yaml, state/rds-mysql.yaml, state/rds-postgres.yaml
Resolves #456 by exposing the ingress security group for `state/*` templates at `SecurityGroupId` to support advanced networking strategies.
I included the same interface in all of the `state/*` templates that include a Security Group (vs. just `rds-postgres`) for consistency, but I can remove some/all of the rest if there's a reason to prefer to limit the scope.
=> Security Group Outputs

state/rds-aurora-serverless-postgres.yaml
=> [Bug Fix] state/rds-aurora-serverless-postgres - Fix MinCapacity and MaxCapacity allowed values

state/rds-aurora-serverless.yaml
see https://aws.amazon.com/about-aws/whats-new/2020/06/announcing-aurora-serverless-with-mysql-5-7-compatibility/
=> Add support for Aurora Serverless MySQL 5.7

wordpress/wordpress-ha.yaml
Enabling RDS Performance Insights for Wordpress. RDS Performance Insights is free for 7 day data retention.
=> [Improvement] wordpress/wordpress-ha: Enabling RDS Performance Insights

wordpress/wordpress-ha.yaml
RDS Performance Insights is not supported for all database instance types.
=> [Bug Fix]  wordpress/wordpress-ha - Enable RDS Performance Insights conditionally

operations/alert.yaml
HTTP/S subscriptions will suffer from huge delays. This is a workaround recommended by AWS. Check out https://cloudonaut.io/loosing-trust-in-aws-sns-broken-for-24-days/ for details.
=> [Bug Fix] operations/alert: Workaround for SNS delay

security/auth-proxy-ha-github-orga.yaml
…-orga.yaml
---
This exposes the `skip_auth_regex` option of the `oauth2-proxy.cfg` file as a CloudFormation parameter.
https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/overview#command-line-options
> bypass authentication for requests paths that match (may be given multiple times)
This should be suitably generic, but is to support a use case where I am running a Jenkins behind an auth proxy, but I want to selectively allow Github to post webhooks directly to Jenkins to notify of changes, and to trigger builds without having to rely on Jenkins polling when behind an auth proxy.
```yaml
Parameters:
SkipAuthRegex: '^\/github-webhook\/$'
```
=> [Improvement] security/auth-proxy-ha-github-orga - Add SkipAuthRegex parameter

security/auth-proxy-ha-github-orga.yaml
https://github.com/oauth2-proxy/oauth2-proxy/releases/tag/v7.0.0
=> [Improvement] security/auth-proxy-ha-github-orga - Update OAuth2 Proxy to 7.0.0

security/auth-proxy-ha-github-orga.yaml
https://github.com/oauth2-proxy/oauth2-proxy/releases/tag/v7.0.1
=> [Bug Fix] security/auth-proxy-ha-github-orga - pdate OAuth2 Proxy to 7.0.1

operations/terraform-state.yaml, state/s3.yaml
Enabling Bucket Keys to [reduce the cost of SSE-KMS](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucket-key.html).
=> [Improvement] state/s3 - Enabling S3 Bucket Keys

security/auth-proxy-ha-github-orga.yaml
https://github.com/oauth2-proxy/oauth2-proxy/releases/tag/v7.1.0
=> [Security] security/auth-proxy-ha-github-orga - Update OAuth2 Proxy to 7.1.0

security/auth-proxy-ha-github-orga.yaml
https://github.com/oauth2-proxy/oauth2-proxy/releases/tag/v7.1.1
=> [Bug Fix] security/auth-proxy-ha-github-orga - Update OAuth2 Proxy to 7.1.1

security/auth-proxy-ha-github-orga.yaml
https://github.com/oauth2-proxy/oauth2-proxy/releases/tag/v7.1.2
=> [Bug Fix] security/auth-proxy-ha-github-orga - Update OAuth2 Proxy to 7.1.2

ecs/service-cluster-alb.yaml, ecs/service-dedicated-alb.yaml, fargate/service-cloudmap.yaml, fargate/service-cluster-alb.yaml, fargate/service-dedicated-alb.yaml
---
I added ecs circuit breakers. this is extremely helpful when a deployment fails because you do not have to wait "forever" until cloud formation notices the deployment isn't working.
=> Add circuit breaker options to ECS Services

wordpress/wordpress-ha-aurora.yaml, wordpress/wordpress-ha.yaml
PHP 7.2 has been EOL for quite some time so I took the liberty to upgrade it to 7.4 within the WordPress templates.
[https://www.php.net/supported-versions.php](https://www.php.net/supported-versions.php)
=> [Improvement] wordpress/* - Upgrade PHP to 7.4

state/elasticache-redis.yaml
When creating the Cluster with more than one Shard the creation fails.
I think this is due to using ReplicationGroup.PrimaryAdress instead of ReplicationGroup.ConfigurationEndPoint for the RecordSet Resource when cluster-mode is on.
ErrorMessage:
```
RecordSet | CREATE_FAILED | Template error: Primary endpoint was not found for replication group abc-test123
```
=> [Bug Fix] state/elasticache-redis - ConfigurationEndPoint if HasClusterModeEnabled instead PrimaryAdress

docs/vpc.md, vpc/vpc-no-bastion.yaml
This template can be used to disable SSH access by deploying an "empty" / non existant bastion host (e.g., when using SSM Session Manager).
=> [New Template] vpc/vpc-no-bastion

ec2/README.md, ecs/README.md, ecs/cluster-cost-optimized.yaml, ecs/cluster.yaml, jenkins/README.md, jenkins/jenkins2-ha-agents.yaml, jenkins/jenkins2-ha.yaml, security/README.md, security/auth-proxy-ha-github-orga.yaml, vpc/README.md, vpc/vpc-nat-instance.yaml, vpc/vpc-ssh-bastion.yaml, vpc/vpc-vpn-bastion.yaml, wordpress/README.md, wordpress/wordpress-ha-aurora.yaml, wordpress/wordpress-ha.yaml
[Security] ecs/cluster* - Update Amazon Linux 2 ECS-optimized to 20211120
[Security] vpc/vpc-nat-instance - Update Amazon Linux NAT-optimized to 20211201.1
=> [Security] * - Update Amazon Linux 2 to 20211201.0

security/auth-proxy-ha-github-orga.yaml
https://github.com/oauth2-proxy/oauth2-proxy/releases/tag/v7.2.1
=> [Security] security/auth-proxy-ha-github-orga - Update OAuth2 Proxy to 7.2.1

wordpress/README.md, wordpress/wordpress-ha-aurora.yaml, wordpress/wordpress-ha.yaml
AWS announced prefix lists containing the IP address ranges of CloudFront. Using this to control traffic from CloudFront to the ALB.
=> [Improvement] wordpress: CloudFront prefix list to control traffic

ecs/service-dedicated-alb.yaml
Should be `aws.ecs` according to the [schema](https://eu-central-1.console.aws.amazon.com/events/home?region=eu-central-1#/registries/aws.events/schemas/aws.ecs%40ECSServiceAction/version/1)
=> fix: invalid source for ECS events

state/dynamodb.yaml
Template: state/dynamodb.yaml
DynamoDB backup jobs were failing, stating that first, dynamodb:ListTagsOfResource was required, then, dynamodb:StartAwsBackupJob was required.
Once these Actions were allowed for the Role, DynamoDB backups started and completed as expected.
https://docs.aws.amazon.com/aws-backup/latest/devguide/security-iam-awsmanpol.html mentions both of these being added to the AWS Backup policy, under "Policy updates for AWS Backup", Date "November 23, 2021"
The specific errors were:
An AWS Backup job failed. Resource ARN : arn:aws:dynamodb:us-west-1:XXXXXXXXXXXX:table/cache. BackupJob ID : XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX Status Message : User: arn:aws:sts::XXXXXXXXXXXX:assumed-role/XXXXXXX-com-DynamoDB-BackupRole-XXXXXXXXXXXXX/AWSBackup-XXXXXXX-com-DynamoDB-BackupRol …
=> [Improvement] state/dynamodb - Support advanced features for AWS Backup DynamoDB backups

ecs/service-cluster-alb.yaml, ecs/service-dedicated-alb.yaml
Currently the ALB only check the root '/' path for health checking. Some images require a custom health check path and is supported by AWS cli / console / cloudformation as well.
=> Adding custom health check paths for ALB

jenkins/jenkins2-ha-agents.yaml, jenkins/jenkins2-ha.yaml
[Bug Fix] jenkins/* - Update Plugin Installation Manager Tool for Jenkins to 2.12.9
https://www.jenkins.io/changelog-stable//#v2.361.2
https://github.com/jenkinsci/plugin-installation-manager-tool/releases/tag/2.12.9
=> [Bug Fix] jenkins/* - Update Jenkins to 2.361.2

wordpress/wordpress-ha-aurora.yaml, wordpress/wordpress-ha.yaml
[Improvement] wordpress/* - Update WP-CLI to 2.7.1
https://wordpress.org/news/2022/10/wordpress-6-0-3-security-release/
=> [Security] wordpress/* - Update WordPress to 6.0.3

security/auth-proxy-ha-github-orga.yaml
https://github.com/oauth2-proxy/oauth2-proxy/releases/tag/v7.4.0
=> [Security] security/auth-proxy-ha-github-orga - Update oauth2-proxy to 7.4.0

state/s3.yaml, test/src/test/java/de/widdix/awscftemplates/operations/TestAccessLogsAnonymizer.java
Broken because of the switch in S3 to disable ACLs by default.
=> [Bug Fix] state/s3 - Fix Access := CloudFrontAccessLogWrite

state/rds-aurora.yaml
`CopyTagsToSnapshot` is now supported on `AWS::RDS::DBCluster` resource(s).
---
`CopyTagsToSnapshot` is now supported on `AWS::RDS::DBCluster` resource(s):
- https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/238
- https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-copytagstosnapshot
=> copy tags to cluster snapshots

wordpress/wordpress-ha-aurora.yaml, wordpress/wordpress-ha.yaml
https://wordpress.org/news/2023/08/wordpress-6-3-1-maintenance-release/
=> [Improvement] wordpress/* - Update WordPress to 6.3.1

security/auth-proxy-ha-github-orga.yaml
https://github.com/oauth2-proxy/oauth2-proxy/releases/tag/v7.5.1
=> [Security] security/auth-proxy-ha-github-orga - Update OAuth2 Proxy to 7.5.1

security/kms-key.yaml
---
Allow CloudFront to service encrypted content from S3 origins. See,  https://aws.amazon.com/blogs/networking-and-content-delivery/serving-sse-kms-encrypted-content-from-s3-using-cloudfront/
=> Allow CloudFront to serve encrypted content from S3

state/s3.yaml
* only S3-SSE is available for *LB log delivery
---
Assume encryption of *LB access logs using S3-SSE if KMS key is provided.
=> encrypt *LB access logs if KMS key is specified
